# 应用信息



# 应用信息结束

server:
  port: 8081
  servlet:
    context-path: /
    path: /

spring:
  application:
    name: wh_service
  jackson:
    time-zone: GMT+8
    mapper:
      accept_case_insensitive_properties: true
  datasource:
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://192.168.50.254:3306/wh_starter?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8
      username: root
      password: hehe
      initial-size: 5
      max-active: 20
      min-idle: 5
      max-wait: 60000
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      validation-query: SELECT 1
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      time-between-eviction-runs-millis: 60000
      filters: stat,slf4j
      min-evictable-idle-time-millis: 300000

# spring boot Actuator
management:
  security:
    enabled: false

# dubbo configuration start


# dubbo configuration end

# mybatis
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    mapUnderscoreToCamelCase: true

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

# swagger
swagger:
  basePackage: com.wh.service.starter.web.host.controller
# swagger end

# dev

